const data=[
    {
        title: "FlowerPot",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/1.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "400.00",
        rating: "★★★★☆",
    },
    {
        title: "Vase",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/2.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "350.00",
        rating: "★★★★☆",
    },
    {
        title: "Bowel",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/3.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "450.00",
        rating: "★★★★☆",
    },
    {
        title: "Bowel",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/4.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "280.00",
        rating: "★★★★☆",
    },
    {
        title: "FishBowel",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/5.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "420.00",
        rating: "★★★★☆",
    },
    {
        title: "Bowel",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/6.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "200.00",
        rating: "★★★★☆",
    },
    {
        title: "TulasiKota",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/7.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "450.00",
        rating: "★★★★☆",
    },
    {
        title: "Coin Bank",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/8.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "100.00",
        rating: "★★★★☆",
    },
    {
        title: "Wall Hanging",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/9.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "200.00",
        rating: "★★★★☆",
    },
    {
        title: "Decorative Bell",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/10.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "250.00",
        rating: "★★★★☆",
    },
    {
        title: "Bowel",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/11.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "350.00",
        rating: "★★★★☆",
    },
    {
        title: "Bell",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/12.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "150.00",
        rating: "★★★★☆",
    },
    {
        title: "Vase",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/13.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "180.00",
        rating: "★★★★☆",
    },
    {
        title: "FlowerPot",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/15.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: ".00",
        rating: "★★★★☆",
    },
    {
        title: "Elephant",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/16.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "800.00",
        rating: "★★★★☆",
    },
    {
        title: "Budda",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/17.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "600.00",
        rating: "★★★★☆",
    },
    {
        title: "Horse",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/18.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "400.00",
        rating: "★★★★☆",
    },
    {
        title: "CookingPot",
        avatar: "https://leadwinner.com/shilparamam2/images2/tera/19.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        price: "180.00",
        rating: "★★★★☆",
    }
]